version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/server

permissions:
  - object: /
    pattern: "**"
    owner: ec2-user
    group: ec2-user

hooks:
  AfterInstall:
    - location: scripts/change-permissions.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/server-start-silent.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: scripts/server-stop.sh
      timeout: 300
      runas: ec2-user
  ValidateService:
    - location: scripts/server-validate.sh
      timeout: 300
      runas: ec2-user