package ca.unb.ktb.application.dao;

import ca.unb.ktb.core.model.PhysicalAddress;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * JPA Repository interface for defining specific DAO methods not already generated by JPA.
 *
 * @author Brandon Richardson
 * */
public interface PhysicalAddressDAO extends JpaRepository<PhysicalAddress, Long> {

}
