package com.unb.beforeigo.application.dao;

import com.unb.beforeigo.core.model.PhysicalAddress;
import org.springframework.data.jpa.repository.JpaRepository;

/**
 * JPA Repository interface for defining specific DAO methods not already generated by JPA.
 *
 * @author Brandon Richardson
 * */
public interface PhysicalAddressDAO extends JpaRepository<PhysicalAddress, Long> {

}
