package com.unb.beforeigo.application.dao;

import com.unb.beforeigo.core.model.User;
import com.unb.beforeigo.core.model.UserRelationship;
import org.springframework.data.jpa.repository.JpaRepository;

import java.util.List;

/**
 * JPA Repository interface for defining specific DAO methods not already generated by JPA.
 *
 * @author Brandon Richardson
 * */
public interface UserRelationshipDAO extends JpaRepository<UserRelationship, Long> {

    /**
     * Retrieve a list of relationships from a given user, i.e. users they are following.
     *
     * @param follower the user that is following another uesr
     * @return list of relationships that the user initiated
     * */
    List<UserRelationship> findByFollower(final User follower);

    /**
     * Retrieve a list of relationships with a given user, i.e. users that follow them.
     *
     * @param user the user that is being followed by another user
     * @return list of relationships that users have initiated with a given user
     * */
    List<UserRelationship> findByFollowing(final User user);
}
